version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: adoorei_app
    container_name: adoorei_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8021:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: adoorei
      MYSQL_USER: adoorei
      MYSQL_PASSWORD: secret # Ajuste feito aqui
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - app-network

volumes:
  dbdata:
    driver: local

networks:
  app-network:
    driver: bridge
