name: PHP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.2.16']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, pcov
          coverage: pcov
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env
        run: cp .env.example .env

      - name: Set Laravel APP_KEY
        run: echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit --coverage-text

      - name: Install phpcs
        run: composer require squizlabs/php_codesniffer

      - name: Check coding standards
        run: ./vendor/bin/phpcs --standard=PSR12 core/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Ananiaslitz/etest
